@token=eyJhbGciOiJSUzI1NiIsImtpZCI6Ik9xUExzR3RpVDJIdVFzTEh0V3gwVEEiLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE2MDM2OTAyNjQsImV4cCI6MTYwMzcyNjI2NCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMCIsImF1ZCI6InNrb3J1YmEiLCJjbGllbnRfaWQiOiJza29ydWJhIiwic3ViIjoiN2M0NDY5NzItMDAwZS00YzExLThkYTMtY2RmN2IyM2JjYjYyIiwiYXV0aF90aW1lIjoxNjAzNjkwMjYzLCJpZHAiOiJsb2NhbCIsInJvbGUiOiJhZG1pbiIsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJyb2xlIiwic2tvcnViYSJdLCJhbXIiOlsicHdkIl19.eX0Ba3NnWXcliT341KkPfoYfUzJHHve4F__JbwEmSfCSAVux9ZPAtr6_dvkPpiiRSY8Iy_gHsEErMSeW3d2EPl5afCdOObsrPa1A-JWGujWS3vsDBrp_k8mPH-5BElrHt_PV42YOew17BSzbm5LMUhLEp4iZtDrzSI4vr5WZ3JBX_IOLJgN0d7G5Mse4Tzblb4HEjxT9XCTZFuR29dy-FQanVHHNRLcE6hvP_sGln_l9UBXtkGmtUhnD33xD951ePmzGwTJdCIr94nNwsM0H0Izoq3_a7lTbuif6eq_UVL9N6iSgm9FZXBelbJB07Cm4BVWDOdOedLpNr7aVFZQnZA

###
GET https://localhost:9000/api/apiResources
Authorization: Bearer {{token}}
###
GET https://localhost:9000/api/apiResourceClaims
Authorization: Bearer {{token}}
###
GET https://localhost:9000/api/apiScopes
Authorization: Bearer {{token}}
###
GET https://localhost:9000/api/apiScopeClaims
Authorization: Bearer {{token}}
###
GET https://localhost:9000/api/apiSecrets
Authorization: Bearer {{token}}
###

