@baseAuthUrl = https://localhost:5000


###
GET {{baseAuthUrl}}/_api/idResources
###
POST {{baseAuthUrl}}/_api/idResources
Content-Type: application/json

  {  
    "name":"role",
    "userClaims":["role"]
  }  
